package edu.cmu.ri.mrpl.TeRK.color;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.KeyStroke;

public class ColorChooserDialog extends JDialog
   {
   private Color originalColor;
   private Color newColor;
   private boolean okPressed = false;

   private JPanel contentPane;
   private JButton buttonOK;
   private JButton buttonCancel;
   private JPanel colorPalettePanel;
   private JPanel originalColorPanel;
   private JPanel newColorPanel;

   private final ColorPalette colorPalette = new ColorPalette(
         new ColorChangeActionListenerStrategy()
         {
         public void actionPerformed(final Color color)
            {
            //peerInfoController.setAttribute("hexColor", ColorUtils.getHexColor(color));
            newColor = color;
            newColorPanel.setBackground(newColor);
            }
         });

   public ColorChooserDialog()
      {
      setTitle("Choose A Color");
      setContentPane(contentPane);
      setModal(true);
      getRootPane().setDefaultButton(buttonOK);

      colorPalettePanel.add(colorPalette);

      buttonOK.addActionListener(new ActionListener()
      {
      public void actionPerformed(ActionEvent e)
         {
         onOK();
         }
      });

      buttonCancel.addActionListener(new ActionListener()
      {
      public void actionPerformed(ActionEvent e)
         {
         onCancel();
         }
      });

      // call onCancel() when cross is clicked
      setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
      addWindowListener(new WindowAdapter()
      {
      public void windowClosing(WindowEvent e)
         {
         onCancel();
         }
      });

      // call onCancel() on ESCAPE
      contentPane.registerKeyboardAction(new ActionListener()
      {
      public void actionPerformed(ActionEvent e)
         {
         onCancel();
         }
      }, KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
      }

   private void onOK()
      {
      // add your code here
      okPressed = true;

      dispose();
      }

   private void onCancel()
      {
      // add your code here if necessary
      okPressed = false;
      dispose();
      }

   public void setOriginalColor(Color color)
      {
      originalColor = color;
      originalColorPanel.setBackground(originalColor);
      }

   public Color getNewColor()
      {
      return newColor;
      }

   public boolean showDialog()
      {
      pack();
      setVisible(true);
      return okPressed;
      }

   public static void main(String[] args)
      {
      ColorChooserDialog dialog = new ColorChooserDialog();
      dialog.pack();
      dialog.setVisible(true);
      }

   {
   // GUI initializer generated by IntelliJ IDEA GUI Designer
   // >>> IMPORTANT!! <<<
   // DO NOT EDIT OR ADD ANY CODE HERE!
   $$$setupUI$$$();
   }

   /** Method generated by IntelliJ IDEA GUI Designer
    * >>> IMPORTANT!! <<<
    * DO NOT edit this method OR call it in your code!
    * @noinspection ALL
    */
   private void $$$setupUI$$$()
      {
      contentPane = new JPanel();
      contentPane.setLayout(new GridBagLayout());
      final JPanel panel1 = new JPanel();
      panel1.setLayout(new GridBagLayout());
      GridBagConstraints gbc;
      gbc = new GridBagConstraints();
      gbc.gridx = 0;
      gbc.gridy = 1;
      gbc.weightx = 1.0;
      gbc.fill = GridBagConstraints.BOTH;
      contentPane.add(panel1, gbc);
      final JPanel panel2 = new JPanel();
      panel2.setLayout(new GridBagLayout());
      gbc = new GridBagConstraints();
      gbc.gridx = 1;
      gbc.gridy = 0;
      gbc.weighty = 1.0;
      gbc.fill = GridBagConstraints.BOTH;
      panel1.add(panel2, gbc);
      buttonOK = new JButton();
      buttonOK.setText("OK");
      gbc = new GridBagConstraints();
      gbc.gridx = 0;
      gbc.gridy = 0;
      gbc.weightx = 1.0;
      gbc.weighty = 1.0;
      gbc.fill = GridBagConstraints.HORIZONTAL;
      gbc.insets = new Insets(5, 5, 5, 5);
      panel2.add(buttonOK, gbc);
      buttonCancel = new JButton();
      buttonCancel.setText("Cancel");
      gbc = new GridBagConstraints();
      gbc.gridx = 1;
      gbc.gridy = 0;
      gbc.weightx = 1.0;
      gbc.weighty = 1.0;
      gbc.fill = GridBagConstraints.HORIZONTAL;
      gbc.insets = new Insets(5, 5, 5, 5);
      panel2.add(buttonCancel, gbc);
      final JPanel panel3 = new JPanel();
      panel3.setLayout(new GridBagLayout());
      gbc = new GridBagConstraints();
      gbc.gridx = 0;
      gbc.gridy = 0;
      gbc.weightx = 1.0;
      gbc.weighty = 1.0;
      gbc.fill = GridBagConstraints.BOTH;
      gbc.insets = new Insets(5, 5, 5, 5);
      contentPane.add(panel3, gbc);
      colorPalettePanel = new JPanel();
      colorPalettePanel.setLayout(new GridBagLayout());
      gbc = new GridBagConstraints();
      gbc.gridx = 0;
      gbc.gridy = 0;
      gbc.gridwidth = 2;
      gbc.weighty = 1.0;
      gbc.fill = GridBagConstraints.BOTH;
      panel3.add(colorPalettePanel, gbc);
      colorPalettePanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-16777216)), null));
      final JLabel label1 = new JLabel();
      label1.setText("Current Color");
      gbc = new GridBagConstraints();
      gbc.gridx = 0;
      gbc.gridy = 1;
      gbc.anchor = GridBagConstraints.WEST;
      panel3.add(label1, gbc);
      originalColorPanel = new JPanel();
      originalColorPanel.setLayout(new GridBagLayout());
      originalColorPanel.setMaximumSize(new Dimension(25, 25));
      originalColorPanel.setMinimumSize(new Dimension(25, 25));
      originalColorPanel.setPreferredSize(new Dimension(25, 25));
      gbc = new GridBagConstraints();
      gbc.gridx = 1;
      gbc.gridy = 1;
      gbc.weightx = 1.0;
      gbc.anchor = GridBagConstraints.WEST;
      gbc.insets = new Insets(5, 5, 5, 5);
      panel3.add(originalColorPanel, gbc);
      originalColorPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-16777216)), null));
      final JLabel label2 = new JLabel();
      label2.setText("New Color");
      gbc = new GridBagConstraints();
      gbc.gridx = 0;
      gbc.gridy = 2;
      gbc.anchor = GridBagConstraints.WEST;
      panel3.add(label2, gbc);
      newColorPanel = new JPanel();
      newColorPanel.setLayout(new GridBagLayout());
      newColorPanel.setMaximumSize(new Dimension(25, 25));
      newColorPanel.setMinimumSize(new Dimension(25, 25));
      newColorPanel.setPreferredSize(new Dimension(25, 25));
      gbc = new GridBagConstraints();
      gbc.gridx = 1;
      gbc.gridy = 2;
      gbc.weightx = 1.0;
      gbc.anchor = GridBagConstraints.WEST;
      gbc.insets = new Insets(5, 5, 5, 5);
      panel3.add(newColorPanel, gbc);
      newColorPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-16777216)), null));
      }

   /** @noinspection ALL */
   public JComponent $$$getRootComponent$$$()
      {
      return contentPane;
      }
   }
