//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     DSS Runtime Version: 2.0.730.3
//     CLR Runtime Version: 2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Microsoft.Ccr.Core;
using Microsoft.Dss.Core.Attributes;
using Microsoft.Dss.ServiceModel.Dssp;
using W3C.Soap;

namespace Robotics.VideoStreamViewer
{    
    
    /// <summary>
    /// VideoStreamViewer Contract class
    /// </summary>
    public sealed class Contract
    {
        
        /// <summary>
        /// The Dss Service contract
        /// </summary>
        [DataMember()]
        public const String Identifier = "http://schemas.tempuri.org/2008/07/videostreamviewer.html";
    }
    
    /// <summary>
    /// The VideoStreamViewer State
    /// </summary>
    [DataContract()]
    public class VideoStreamViewerState
    {
    }
    
    /// <summary>
    /// VideoStreamViewer Main Operations Port
    /// </summary>
    [ServicePort()]
    public class VideoStreamViewerOperations : PortSet<DsspDefaultLookup, DsspDefaultDrop, Get, Replace, DrawFrame>
    {
    }
    
    /// <summary>
    /// VideoStreamViewer Get Operation
    /// </summary>
    public class Get : Get<GetRequestType, PortSet<VideoStreamViewerState, Fault>>
    {
        
        /// <summary>
        /// VideoStreamViewer Get Operation
        /// </summary>
        public Get()
        {
        }
        
        /// <summary>
        /// VideoStreamViewer Get Operation
        /// </summary>
        public Get(Microsoft.Dss.ServiceModel.Dssp.GetRequestType body) : 
                base(body)
        {
        }
        
        /// <summary>
        /// VideoStreamViewer Get Operation
        /// </summary>
        public Get(Microsoft.Dss.ServiceModel.Dssp.GetRequestType body, Microsoft.Ccr.Core.PortSet<VideoStreamViewerState,W3C.Soap.Fault> responsePort) : 
                base(body, responsePort)
        {
        }
    }

    public class Replace : Microsoft.Dss.ServiceModel.Dssp.Replace<VideoStreamViewerState, PortSet<DefaultReplaceResponseType, Fault>>
    {
    }

    public class DrawFrame : Update<DrawFrameRequest, PortSet<DefaultUpdateResponseType, Fault>>
    {
        public DrawFrame()
        {
            if (Body == null)
            {
                this.Body = new DrawFrameRequest();
            }
        }

        public DrawFrame(DrawFrameRequest req)
        {
            this.Body = req;
        }
    }

    [DataContract]
    public class DrawFrameRequest
    {
        byte[] _imageData;

        [DataMember]
        public byte[] ImageData
        {
            get { return _imageData; }
            set
            {
                _imageData = new byte[value.Length];
                Array.Copy(value, _imageData, value.Length);
            }
        }
    }
}
